### ISSUE TITLE
Reference demo

### ISSUE THREAD

**Issue by vilbht** [callmecavs/gotem#1]
Hi  Michael,

Is there a demo to see how it functions? JS noob here

Thanks

**Comment by callmecavs** [comment]
@vilav hey man, at this time, all I have is the [example code](https://github.com/callmecavs/gotem#use). its just a simple function that accepts 2 elements, and then an optional object of callback functions

take a look at the [manual test file](https://github.com/callmecavs/gotem/blob/master/test/manual.html) code too
