### ISSUE TITLE
Advantages over clipboard.js ?

### ISSUE THREAD

**Issue by Offirmo** [callmecavs/gotem#4]
Could you explain the advantages of your solution over the venerable https://github.com/zenorocha/clipboard.js and its 16.000 stars ?

**Comment by callmecavs** [comment]
this module is much narrower in scope, and does significantly less under the hood. its a mere one function (40 LOC), and supports only what is (imo) the most common use case for copy to clipboard - click one element, copy the text of another.

`clipboard` is a great library. it has many more options, events, etc - but I don't need any of them. it's also much larger, at 350 LOC.

not better, not worse, just much bigger (300 bytes vs 3kb)
