### ISSUE TITLE
Question about the library to be hosted by CDNJS

### ISSUE THREAD

**Issue by extend1994** [callmecavs/gotem#5]
Hi,
I created a pull request cdnjs/cdnjs#10795 for the library, and it's merged now, but we still have a question.
The question is "Do we need both `gotem.js` and `gotem.module.js`? Or just `gotem.js` for the browsers? "
Thank you!

**Comment by callmecavs** [comment]
@extend1994 hey! I responded on the issue in the CDNJS repo. you'll only need `gotem.js`.

thank you again for taking the time to submit the library and go back and forth with the CDNJS maintainers 👍

**Comment by extend1994** [comment]
@callmecavs Thank you for your response and contribution!
